# Generated by Django 4.2.29 on 2026-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_userpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='crop_recommendations',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='soil_analysis',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='systemknowledge_updates',
            field=models.BooleanField(default=False),
        ),
    ]
