# Generated by Django 5.2.12 on 2026-04-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltest',
            name='organic_matter',
            field=models.FloatField(default=0),
        ),
    ]
