# Generated by Django 4.2.30 on 2026-04-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_soiltest_organic_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='soiltest',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
