# Generated by Django 4.2.30 on 2026-05-03 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soil', '0003_soiltest_confidence_soiltest_soil_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soiltest',
            options={'ordering': ['-test_date']},
        ),
        migrations.RenameField(
            model_name='soiltest',
            old_name='confidence',
            new_name='boron',
        ),
        migrations.RemoveField(
            model_name='soiltest',
            name='data_file',
        ),
        migrations.RemoveField(
            model_name='soiltest',
            name='image',
        ),
        migrations.RemoveField(
            model_name='soiltest',
            name='organic_matter',
        ),
        migrations.RemoveField(
            model_name='soiltest',
            name='soil_score',
        ),
        migrations.AddField(
            model_name='soiltest',
            name='copper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='field_name',
            field=models.CharField(default='Unknown Field', max_length=100),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='lab_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='manganese',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='organic_carbon',
            field=models.FloatField(blank=True, help_text='Organic carbon %', null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='sample_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('scheduled', 'Scheduled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='sulfur',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='test_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='texture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soiltest',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='moisture',
            field=models.FloatField(blank=True, help_text='Moisture %', null=True),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='nitrogen',
            field=models.FloatField(default=0, help_text='Nitrogen (N) in kg/ha'),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='ph',
            field=models.FloatField(default=7, help_text='Soil pH level'),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='phosphorus',
            field=models.FloatField(default=0, help_text='Phosphorus (P) in kg/ha'),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='potassium',
            field=models.FloatField(default=0, help_text='Potassium (K) in kg/ha'),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SoilRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('amendment', 'Soil Amendment'), ('irrigation', 'Irrigation'), ('crop', 'Crop Selection'), ('general', 'General')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('action_required', models.TextField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soil_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='soil.soiltest')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='soil_images/')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('predicted_soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_moisture', models.CharField(blank=True, max_length=50, null=True)),
                ('predicted_fertility', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('soil_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='soil.soiltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
