# Generated by Django 4.2.30 on 2026-05-03 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soil', '0004_alter_soiltest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='nitrogen',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='organic_carbon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='ph',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='phosphorus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='potassium',
            field=models.FloatField(default=0),
        ),
    ]
