# Generated by Django 4.2.30 on 2026-05-11 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0005_alter_soilimage_user_alter_soiltest_moisture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soiltest',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
