# Generated by Django 4.2.30 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0006_alter_soiltest_test_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soilrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='soiltest',
            options={'ordering': ['-test_date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('scheduled', 'Scheduled')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='soiltest',
            name='test_date',
            field=models.DateField(),
        ),
    ]
