# Generated by Django 4.2.30 on 2026-05-14 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0007_alter_soilrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soilrecommendation',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AlterField(
            model_name='soilrecommendation',
            name='category',
            field=models.CharField(choices=[('fertilizer', 'Fertilizer'), ('amendment', 'Soil Amendment'), ('irrigation', 'Irrigation'), ('general', 'General')], max_length=20),
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('soil_reason', models.TextField(blank=True, null=True)),
                ('nutrient_notes', models.TextField(blank=True, null=True)),
                ('climate_notes', models.TextField(blank=True, null=True)),
                ('suitability_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soil_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='soil.soiltest')),
            ],
            options={
                'ordering': ['-suitability_score'],
            },
        ),
    ]
