# Generated by Django 4.2.30 on 2026-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0008_alter_soilrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
