# Generated by Django 4.2.30 on 2026-05-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0009_croprecommendation_extra_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croprecommendation',
            options={'ordering': ['-suitability_score', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='soilrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='soilrecommendation',
            name='category',
            field=models.CharField(choices=[('fertilizer', 'Fertilizer'), ('amendment', 'Soil Amendment'), ('irrigation', 'Irrigation'), ('crop', 'Crop'), ('general', 'General')], max_length=20),
        ),
    ]
